apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: httpbin
  name: httpbin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: httpbin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/httpbin-default: "true"
        io.kompose.service: httpbin
    spec:
      containers:
        - image: kennethreitz/httpbin
          name: httpbin
          ports:
            - containerPort: 80
              hostPort: 5000
              protocol: TCP
          resources: {}
      hostname: httpbin
      restartPolicy: Always
status: {}
