apiVersion: v1
kind: Service
metadata:
  name: ua
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: ua
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ua
  template:
    metadata:
      labels:
        app: ua
    spec:
      containers:
        - name: ua
          image: pkapsalismartel/ua:v0.22
          ports:
            - containerPort: 8000
